// Grade 5 Math Curriculum aligned with Khan Academy structure

import { Lesson } from './types'

export const khanAcademyGrade5Lessons: Lesson[] = [
  // Unit 1: Decimal Place Value
  {
    id: 'decimal-place-value-intro',
    title: 'Introduction to Decimals',
    description: 'What are decimals?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 1,
    estimatedTime: 18,
  },
  {
    id: 'decimal-place-value-tenths',
    title: 'Tenths and Hundredths',
    description: 'Learn about tenths and hundredths!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 2,
    estimatedTime: 20,
  },
  {
    id: 'decimal-place-value-thousandths',
    title: 'Thousandths',
    description: 'Learn about thousandths!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 3,
    estimatedTime: 19,
  },
  {
    id: 'comparing-decimals',
    title: 'Comparing Decimals',
    description: 'Which decimal is bigger?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 4,
    estimatedTime: 19,
  },
  {
    id: 'rounding-decimals',
    title: 'Rounding Decimals',
    description: 'Round decimals to make them easier!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 5,
    estimatedTime: 20,
  },

  // Unit 2: Add Decimals
  {
    id: 'add-decimals-tenths',
    title: 'Adding Decimals - Tenths',
    description: 'Add decimals with tenths!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 6,
    estimatedTime: 20,
  },
  {
    id: 'add-decimals-hundredths',
    title: 'Adding Decimals - Hundredths',
    description: 'Add decimals with hundredths!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 7,
    estimatedTime: 21,
  },
  {
    id: 'add-decimals-word',
    title: 'Adding Decimals Word Problems',
    description: 'Solve real problems with adding decimals!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 8,
    estimatedTime: 22,
  },

  // Unit 3: Subtract Decimals
  {
    id: 'subtract-decimals-tenths',
    title: 'Subtracting Decimals - Tenths',
    description: 'Subtract decimals with tenths!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 9,
    estimatedTime: 20,
  },
  {
    id: 'subtract-decimals-hundredths',
    title: 'Subtracting Decimals - Hundredths',
    description: 'Subtract decimals with hundredths!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 10,
    estimatedTime: 21,
  },
  {
    id: 'subtract-decimals-word',
    title: 'Subtracting Decimals Word Problems',
    description: 'Solve real problems with subtracting decimals!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 11,
    estimatedTime: 22,
  },

  // Unit 4: Multi-Digit Multiplication
  {
    id: 'multiply-2-digit',
    title: 'Multiply by 2-Digit Numbers',
    description: 'Learn to multiply by 2-digit numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 12,
    estimatedTime: 25,
  },
  {
    id: 'multiply-3-digit',
    title: 'Multiply by 3-Digit Numbers',
    description: 'Learn to multiply by 3-digit numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 13,
    estimatedTime: 26,
  },
  {
    id: 'multiply-area-model',
    title: 'Area Model for Multiplication',
    description: 'Use boxes to help you multiply!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 14,
    estimatedTime: 23,
  },
  {
    id: 'multiply-word-problems',
    title: 'Multiplication Word Problems',
    description: 'Solve real problems with multiplication!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 15,
    estimatedTime: 24,
  },

  // Unit 5: Multi-Digit Division
  {
    id: 'divide-2-digit',
    title: 'Divide by 2-Digit Numbers',
    description: 'Learn to divide by 2-digit numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 16,
    estimatedTime: 25,
  },
  {
    id: 'divide-remainders',
    title: 'Division with Remainders',
    description: 'Sometimes numbers don\'t divide evenly!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 17,
    estimatedTime: 22,
  },
  {
    id: 'divide-partial-quotients',
    title: 'Partial Quotients',
    description: 'Another way to divide!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 18,
    estimatedTime: 23,
  },
  {
    id: 'divide-word-problems',
    title: 'Division Word Problems',
    description: 'Solve real problems with division!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 19,
    estimatedTime: 24,
  },

  // Unit 6: Multiply Decimals
  {
    id: 'multiply-decimals-tenths',
    title: 'Multiply Decimals - Tenths',
    description: 'Multiply decimals with tenths!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 20,
    estimatedTime: 22,
  },
  {
    id: 'multiply-decimals-hundredths',
    title: 'Multiply Decimals - Hundredths',
    description: 'Multiply decimals with hundredths!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 21,
    estimatedTime: 23,
  },
  {
    id: 'multiply-decimals-word',
    title: 'Multiply Decimals Word Problems',
    description: 'Solve real problems with multiplying decimals!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 22,
    estimatedTime: 24,
  },

  // Unit 7: Divide Decimals
  {
    id: 'divide-decimals-tenths',
    title: 'Divide Decimals - Tenths',
    description: 'Divide decimals with tenths!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 23,
    estimatedTime: 22,
  },
  {
    id: 'divide-decimals-hundredths',
    title: 'Divide Decimals - Hundredths',
    description: 'Divide decimals with hundredths!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 24,
    estimatedTime: 23,
  },
  {
    id: 'divide-decimals-word',
    title: 'Divide Decimals Word Problems',
    description: 'Solve real problems with dividing decimals!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 25,
    estimatedTime: 24,
  },

  // Unit 8: Add and Subtract Fractions
  {
    id: 'add-fractions-like',
    title: 'Add Fractions with Same Bottom',
    description: 'Add fractions that have the same denominator!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 26,
    estimatedTime: 20,
  },
  {
    id: 'subtract-fractions-like',
    title: 'Subtract Fractions with Same Bottom',
    description: 'Subtract fractions that have the same denominator!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 27,
    estimatedTime: 20,
  },
  {
    id: 'add-fractions-unlike',
    title: 'Add Fractions with Different Bottoms',
    description: 'Add fractions with different denominators!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 28,
    estimatedTime: 25,
  },
  {
    id: 'subtract-fractions-unlike',
    title: 'Subtract Fractions with Different Bottoms',
    description: 'Subtract fractions with different denominators!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 29,
    estimatedTime: 25,
  },
  {
    id: 'add-subtract-mixed',
    title: 'Add and Subtract Mixed Numbers',
    description: 'Work with whole numbers and fractions together!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 30,
    estimatedTime: 26,
  },

  // Unit 9: Multiply Fractions
  {
    id: 'multiply-fractions',
    title: 'Multiply Fractions',
    description: 'Learn to multiply fractions!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 31,
    estimatedTime: 22,
  },
  {
    id: 'multiply-fractions-mixed',
    title: 'Multiply Mixed Numbers',
    description: 'Multiply whole numbers and fractions!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 32,
    estimatedTime: 24,
  },
  {
    id: 'multiply-fractions-word',
    title: 'Multiply Fractions Word Problems',
    description: 'Solve real problems with fraction multiplication!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 33,
    estimatedTime: 23,
  },

  // Unit 10: Divide Fractions
  {
    id: 'divide-fractions',
    title: 'Divide Fractions',
    description: 'Learn to divide fractions!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 34,
    estimatedTime: 23,
  },
  {
    id: 'divide-fractions-mixed',
    title: 'Divide Mixed Numbers',
    description: 'Divide whole numbers and fractions!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 35,
    estimatedTime: 25,
  },
  {
    id: 'divide-fractions-word',
    title: 'Divide Fractions Word Problems',
    description: 'Solve real problems with fraction division!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '5',
    order: 36,
    estimatedTime: 24,
  },

  // Unit 11: Powers of 10
  {
    id: 'powers-ten-intro',
    title: 'Powers of 10',
    description: 'Learn about 10, 100, 1000, and more!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 37,
    estimatedTime: 20,
  },
  {
    id: 'multiply-powers-ten',
    title: 'Multiply by Powers of 10',
    description: 'Multiply by 10, 100, 1000!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 38,
    estimatedTime: 21,
  },
  {
    id: 'divide-powers-ten',
    title: 'Divide by Powers of 10',
    description: 'Divide by 10, 100, 1000!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '5',
    order: 39,
    estimatedTime: 21,
  },

  // Unit 12: Volume
  {
    id: 'volume-intro',
    title: 'What is Volume?',
    description: 'Learn what volume means!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '5',
    order: 40,
    estimatedTime: 18,
  },
  {
    id: 'volume-formula',
    title: 'Volume Formula',
    description: 'Find volume using length, width, and height!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '5',
    order: 41,
    estimatedTime: 22,
  },
  {
    id: 'volume-unit-cubes',
    title: 'Volume with Unit Cubes',
    description: 'Count cubes to find volume!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '5',
    order: 42,
    estimatedTime: 20,
  },
  {
    id: 'volume-word-problems',
    title: 'Volume Word Problems',
    description: 'Solve real problems with volume!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '5',
    order: 43,
    estimatedTime: 23,
  },

  // Unit 13: Coordinate Plane
  {
    id: 'coordinate-plane-intro',
    title: 'Introduction to Coordinate Plane',
    description: 'Learn about the coordinate plane!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '5',
    order: 44,
    estimatedTime: 19,
  },
  {
    id: 'coordinate-plane-plotting',
    title: 'Plotting Points',
    description: 'Learn to plot points on the coordinate plane!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '5',
    order: 45,
    estimatedTime: 20,
  },
  {
    id: 'coordinate-plane-reading',
    title: 'Reading Coordinates',
    description: 'Learn to read coordinates!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '5',
    order: 46,
    estimatedTime: 19,
  },
]

