// Grade 8 Math Curriculum aligned with Khan Academy structure

import { Lesson } from './types'

export const khanAcademyGrade8Lessons: Lesson[] = [
  // Unit 1: Numbers and Operations
  {
    id: 'irrational-numbers',
    title: 'Irrational Numbers',
    description: 'What are irrational numbers?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '8',
    order: 1,
    estimatedTime: 21,
  },
  {
    id: 'approximating-irrational',
    title: 'Approximating Irrational Numbers',
    description: 'Estimate irrational numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '8',
    order: 2,
    estimatedTime: 22,
  },
  {
    id: 'scientific-notation',
    title: 'Scientific Notation',
    description: 'Write very big and very small numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '8',
    order: 3,
    estimatedTime: 23,
  },

  // Unit 2: Solving Equations
  {
    id: 'equations-review',
    title: 'Equations Review',
    description: 'Review solving equations!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 4,
    estimatedTime: 20,
  },
  {
    id: 'equations-variables-both',
    title: 'Equations with Variables on Both Sides',
    description: 'Solve equations with variables on both sides!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 5,
    estimatedTime: 24,
  },
  {
    id: 'equations-multi-step',
    title: 'Multi-Step Equations',
    description: 'Solve equations with many steps!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 6,
    estimatedTime: 25,
  },
  {
    id: 'equations-word-problems',
    title: 'Equation Word Problems',
    description: 'Solve real problems with equations!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 7,
    estimatedTime: 26,
  },

  // Unit 3: Linear Equations and Functions
  {
    id: 'linear-equations-intro',
    title: 'Introduction to Linear Equations',
    description: 'What are linear equations?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 8,
    estimatedTime: 22,
  },
  {
    id: 'linear-equations-slope',
    title: 'Slope',
    description: 'Learn about slope!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 9,
    estimatedTime: 23,
  },
  {
    id: 'linear-equations-intercept',
    title: 'Y-Intercept',
    description: 'Learn about y-intercept!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 10,
    estimatedTime: 22,
  },
  {
    id: 'linear-equations-graph',
    title: 'Graphing Linear Equations',
    description: 'Learn to graph linear equations!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 11,
    estimatedTime: 24,
  },
  {
    id: 'linear-equations-slope-intercept',
    title: 'Slope-Intercept Form',
    description: 'Write equations in slope-intercept form!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 12,
    estimatedTime: 23,
  },

  // Unit 4: Systems of Equations
  {
    id: 'systems-intro',
    title: 'Introduction to Systems of Equations',
    description: 'What are systems of equations?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 13,
    estimatedTime: 22,
  },
  {
    id: 'systems-graphing',
    title: 'Solving Systems by Graphing',
    description: 'Solve systems by graphing!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 14,
    estimatedTime: 24,
  },
  {
    id: 'systems-substitution',
    title: 'Solving Systems by Substitution',
    description: 'Solve systems by substitution!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 15,
    estimatedTime: 25,
  },
  {
    id: 'systems-elimination',
    title: 'Solving Systems by Elimination',
    description: 'Solve systems by elimination!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 16,
    estimatedTime: 25,
  },
  {
    id: 'systems-word-problems',
    title: 'Systems Word Problems',
    description: 'Solve real problems with systems!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '8',
    order: 17,
    estimatedTime: 26,
  },

  // Unit 5: Geometry - Transformations
  {
    id: 'transformations-intro',
    title: 'Introduction to Transformations',
    description: 'What are transformations?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 18,
    estimatedTime: 21,
  },
  {
    id: 'transformations-translations',
    title: 'Translations',
    description: 'Learn about translations!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 19,
    estimatedTime: 22,
  },
  {
    id: 'transformations-reflections',
    title: 'Reflections',
    description: 'Learn about reflections!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 20,
    estimatedTime: 22,
  },
  {
    id: 'transformations-rotations',
    title: 'Rotations',
    description: 'Learn about rotations!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 21,
    estimatedTime: 23,
  },
  {
    id: 'transformations-dilations',
    title: 'Dilations',
    description: 'Learn about dilations!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 22,
    estimatedTime: 23,
  },

  // Unit 6: Geometry - Congruence and Similarity
  {
    id: 'congruence-intro',
    title: 'Introduction to Congruence',
    description: 'What is congruence?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 23,
    estimatedTime: 21,
  },
  {
    id: 'similarity-intro',
    title: 'Introduction to Similarity',
    description: 'What is similarity?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 24,
    estimatedTime: 21,
  },
  {
    id: 'similarity-triangles',
    title: 'Similar Triangles',
    description: 'Learn about similar triangles!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 25,
    estimatedTime: 23,
  },

  // Unit 7: Pythagorean Theorem
  {
    id: 'pythagorean-intro',
    title: 'Introduction to Pythagorean Theorem',
    description: 'What is the Pythagorean theorem?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 26,
    estimatedTime: 22,
  },
  {
    id: 'pythagorean-find-hypotenuse',
    title: 'Finding the Hypotenuse',
    description: 'Use the Pythagorean theorem to find the hypotenuse!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 27,
    estimatedTime: 23,
  },
  {
    id: 'pythagorean-find-leg',
    title: 'Finding a Leg',
    description: 'Use the Pythagorean theorem to find a leg!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 28,
    estimatedTime: 23,
  },
  {
    id: 'pythagorean-word-problems',
    title: 'Pythagorean Theorem Word Problems',
    description: 'Solve real problems with the Pythagorean theorem!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '8',
    order: 29,
    estimatedTime: 24,
  },

  // Unit 8: Exponents and Radicals
  {
    id: 'exponents-review',
    title: 'Exponents Review',
    description: 'Review exponents!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '8',
    order: 30,
    estimatedTime: 21,
  },
  {
    id: 'exponents-rules',
    title: 'Exponent Rules',
    description: 'Learn the rules for exponents!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '8',
    order: 31,
    estimatedTime: 23,
  },
  {
    id: 'radicals-intro',
    title: 'Introduction to Radicals',
    description: 'What are radicals?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '8',
    order: 32,
    estimatedTime: 22,
  },
  {
    id: 'radicals-simplify',
    title: 'Simplifying Radicals',
    description: 'Learn to simplify radicals!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '8',
    order: 33,
    estimatedTime: 23,
  },
]

