// Grade 7 Math Curriculum aligned with Khan Academy structure

import { Lesson } from './types'

export const khanAcademyGrade7Lessons: Lesson[] = [
  // Unit 1: Proportional Relationships
  {
    id: 'proportional-relationships-intro',
    title: 'Introduction to Proportional Relationships',
    description: 'What are proportional relationships?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '7',
    order: 1,
    estimatedTime: 21,
  },
  {
    id: 'proportional-relationships-graphs',
    title: 'Proportional Relationships in Graphs',
    description: 'See proportional relationships on graphs!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '7',
    order: 2,
    estimatedTime: 22,
  },
  {
    id: 'proportional-relationships-equations',
    title: 'Proportional Relationships in Equations',
    description: 'Write equations for proportional relationships!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '7',
    order: 3,
    estimatedTime: 23,
  },

  // Unit 2: Rates and Percentages
  {
    id: 'rates-percentages',
    title: 'Rates and Percentages',
    description: 'Work with rates and percentages!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '7',
    order: 4,
    estimatedTime: 22,
  },
  {
    id: 'percent-change',
    title: 'Percent Change',
    description: 'Find how much something changed!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '7',
    order: 5,
    estimatedTime: 23,
  },
  {
    id: 'percent-error',
    title: 'Percent Error',
    description: 'Find how close your answer is!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '7',
    order: 6,
    estimatedTime: 22,
  },

  // Unit 3: Rational Numbers
  {
    id: 'rational-numbers-intro',
    title: 'Introduction to Rational Numbers',
    description: 'What are rational numbers?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '7',
    order: 7,
    estimatedTime: 20,
  },
  {
    id: 'rational-numbers-add',
    title: 'Adding Rational Numbers',
    description: 'Learn to add rational numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '7',
    order: 8,
    estimatedTime: 22,
  },
  {
    id: 'rational-numbers-subtract',
    title: 'Subtracting Rational Numbers',
    description: 'Learn to subtract rational numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '7',
    order: 9,
    estimatedTime: 22,
  },
  {
    id: 'rational-numbers-multiply',
    title: 'Multiplying Rational Numbers',
    description: 'Learn to multiply rational numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '7',
    order: 10,
    estimatedTime: 23,
  },
  {
    id: 'rational-numbers-divide',
    title: 'Dividing Rational Numbers',
    description: 'Learn to divide rational numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '7',
    order: 11,
    estimatedTime: 23,
  },

  // Unit 4: Expressions and Equations
  {
    id: 'expressions-expand',
    title: 'Expanding Expressions',
    description: 'Learn to expand expressions!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '7',
    order: 12,
    estimatedTime: 22,
  },
  {
    id: 'expressions-factor',
    title: 'Factoring Expressions',
    description: 'Learn to factor expressions!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '7',
    order: 13,
    estimatedTime: 23,
  },
  {
    id: 'two-step-equations',
    title: 'Two-Step Equations',
    description: 'Solve equations with two steps!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '7',
    order: 14,
    estimatedTime: 24,
  },
  {
    id: 'equations-word-problems',
    title: 'Equation Word Problems',
    description: 'Solve real problems with equations!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '7',
    order: 15,
    estimatedTime: 25,
  },

  // Unit 5: Inequalities
  {
    id: 'inequalities-intro',
    title: 'Introduction to Inequalities',
    description: 'What are inequalities?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '7',
    order: 16,
    estimatedTime: 21,
  },
  {
    id: 'inequalities-solve',
    title: 'Solving Inequalities',
    description: 'Learn to solve inequalities!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '7',
    order: 17,
    estimatedTime: 22,
  },
  {
    id: 'inequalities-graph',
    title: 'Graphing Inequalities',
    description: 'Show inequalities on a number line!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '7',
    order: 18,
    estimatedTime: 23,
  },

  // Unit 6: Geometry - Scale Drawings
  {
    id: 'scale-drawings-intro',
    title: 'Introduction to Scale Drawings',
    description: 'What are scale drawings?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '7',
    order: 19,
    estimatedTime: 21,
  },
  {
    id: 'scale-drawings-create',
    title: 'Creating Scale Drawings',
    description: 'Learn to make scale drawings!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '7',
    order: 20,
    estimatedTime: 22,
  },
  {
    id: 'scale-drawings-word',
    title: 'Scale Drawing Word Problems',
    description: 'Solve real problems with scale drawings!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '7',
    order: 21,
    estimatedTime: 23,
  },

  // Unit 7: Geometry - Circles
  {
    id: 'circles-intro',
    title: 'Introduction to Circles',
    description: 'Learn about circles!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '7',
    order: 22,
    estimatedTime: 20,
  },
  {
    id: 'circles-area',
    title: 'Area of Circles',
    description: 'Find the area of circles!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '7',
    order: 23,
    estimatedTime: 22,
  },
  {
    id: 'circles-circumference',
    title: 'Circumference of Circles',
    description: 'Find the distance around circles!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '7',
    order: 24,
    estimatedTime: 22,
  },

  // Unit 8: Geometry - Angles
  {
    id: 'angles-complementary',
    title: 'Complementary Angles',
    description: 'Learn about complementary angles!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '7',
    order: 25,
    estimatedTime: 20,
  },
  {
    id: 'angles-supplementary',
    title: 'Supplementary Angles',
    description: 'Learn about supplementary angles!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '7',
    order: 26,
    estimatedTime: 20,
  },
  {
    id: 'angles-vertical',
    title: 'Vertical Angles',
    description: 'Learn about vertical angles!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '7',
    order: 27,
    estimatedTime: 21,
  },

  // Unit 9: Statistics and Probability
  {
    id: 'statistics-samples',
    title: 'Samples and Populations',
    description: 'Learn about samples and populations!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '7',
    order: 28,
    estimatedTime: 21,
  },
  {
    id: 'probability-intro',
    title: 'Introduction to Probability',
    description: 'What is probability?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '7',
    order: 29,
    estimatedTime: 20,
  },
  {
    id: 'probability-events',
    title: 'Probability of Events',
    description: 'Find the chance of things happening!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '7',
    order: 30,
    estimatedTime: 22,
  },
  {
    id: 'probability-compound',
    title: 'Compound Events',
    description: 'Find probability of multiple events!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '7',
    order: 31,
    estimatedTime: 23,
  },
]

