// Grade 3 Math Curriculum aligned with Khan Academy structure

import { Lesson } from './types'

export const khanAcademyGrade3Lessons: Lesson[] = [
  // Unit 1: Intro to Multiplication
  {
    id: 'multiply-intro',
    title: 'What is Multiplication?',
    description: 'Learn what multiplication means!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 1,
    estimatedTime: 18,
  },
  {
    id: 'multiply-groups',
    title: 'Multiplication as Groups',
    description: 'See how groups help us multiply!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 2,
    estimatedTime: 20,
  },
  {
    id: 'multiply-arrays',
    title: 'Multiplication with Arrays',
    description: 'Use arrays to multiply!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 3,
    estimatedTime: 19,
  },

  // Unit 2: 1-Digit Multiplication
  {
    id: 'multiply-1-digit',
    title: 'Multiply by 1-Digit Numbers',
    description: 'Learn to multiply small numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 4,
    estimatedTime: 22,
  },
  {
    id: 'multiply-tables',
    title: 'Times Tables',
    description: 'Memorize your times tables!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 5,
    estimatedTime: 25,
  },
  {
    id: 'multiply-word-problems',
    title: 'Multiplication Word Problems',
    description: 'Solve real problems with multiplication!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 6,
    estimatedTime: 20,
  },

  // Unit 3: Addition, Subtraction, and Estimation
  {
    id: 'add-subtract-review',
    title: 'Adding and Subtracting Review',
    description: 'Review how to add and subtract!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 7,
    estimatedTime: 15,
  },
  {
    id: 'add-subtract-1000',
    title: 'Add and Subtract to 1000',
    description: 'Work with bigger numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 8,
    estimatedTime: 20,
  },
  {
    id: 'rounding-estimation',
    title: 'Rounding and Estimation',
    description: 'Round numbers to make them easier!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 9,
    estimatedTime: 18,
  },

  // Unit 4: Intro to Division
  {
    id: 'division-intro',
    title: 'What is Division?',
    description: 'Learn what division means!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 10,
    estimatedTime: 18,
  },
  {
    id: 'division-groups',
    title: 'Division as Sharing',
    description: 'Share things equally!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 11,
    estimatedTime: 19,
  },
  {
    id: 'division-facts',
    title: 'Division Facts',
    description: 'Learn division facts!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '3',
    order: 12,
    estimatedTime: 20,
  },

  // Unit 5: Understand Fractions
  {
    id: 'fractions-intro',
    title: 'What are Fractions?',
    description: 'Learn about parts of a whole!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '3',
    order: 13,
    estimatedTime: 18,
  },
  {
    id: 'fractions-visual',
    title: 'Fractions as Parts',
    description: 'See fractions as parts of shapes!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '3',
    order: 14,
    estimatedTime: 17,
  },
  {
    id: 'fractions-number-line',
    title: 'Fractions on a Number Line',
    description: 'Put fractions on a number line!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '3',
    order: 15,
    estimatedTime: 19,
  },
  {
    id: 'equivalent-fractions',
    title: 'Equivalent Fractions',
    description: 'Find fractions that are the same!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '3',
    order: 16,
    estimatedTime: 20,
  },
  {
    id: 'comparing-fractions',
    title: 'Comparing Fractions',
    description: 'Which fraction is bigger?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'fractions',
    grade: '3',
    order: 17,
    estimatedTime: 19,
  },

  // Unit 6: Area
  {
    id: 'area-intro',
    title: 'What is Area?',
    description: 'Learn what area means!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '3',
    order: 18,
    estimatedTime: 17,
  },
  {
    id: 'area-counting',
    title: 'Area by Counting',
    description: 'Count squares to find area!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '3',
    order: 19,
    estimatedTime: 18,
  },
  {
    id: 'area-rectangles',
    title: 'Area of Rectangles',
    description: 'Find the area of rectangles!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '3',
    order: 20,
    estimatedTime: 20,
  },

  // Unit 7: Perimeter
  {
    id: 'perimeter-intro',
    title: 'What is Perimeter?',
    description: 'Learn what perimeter means!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '3',
    order: 21,
    estimatedTime: 16,
  },
  {
    id: 'perimeter-shapes',
    title: 'Perimeter of Shapes',
    description: 'Find the perimeter of different shapes!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '3',
    order: 22,
    estimatedTime: 18,
  },

  // Unit 8: Time
  {
    id: 'time-telling',
    title: 'Telling Time',
    description: 'Learn to read clocks!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '3',
    order: 23,
    estimatedTime: 18,
  },
  {
    id: 'time-elapsed',
    title: 'Elapsed Time',
    description: 'How much time has passed?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '3',
    order: 24,
    estimatedTime: 19,
  },

  // Unit 9: Measurement
  {
    id: 'measurement-length',
    title: 'Measuring Length',
    description: 'Measure things with rulers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '3',
    order: 25,
    estimatedTime: 17,
  },
  {
    id: 'measurement-mass',
    title: 'Mass and Weight',
    description: 'Learn about weight and mass!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '3',
    order: 26,
    estimatedTime: 18,
  },
  {
    id: 'measurement-volume',
    title: 'Volume',
    description: 'Learn about volume!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '3',
    order: 27,
    estimatedTime: 17,
  },

  // Unit 10: Data
  {
    id: 'data-pictographs',
    title: 'Pictographs',
    description: 'Read and make pictographs!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '3',
    order: 28,
    estimatedTime: 18,
  },
  {
    id: 'data-bar-graphs',
    title: 'Bar Graphs',
    description: 'Read and make bar graphs!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '3',
    order: 29,
    estimatedTime: 19,
  },
  {
    id: 'data-line-plots',
    title: 'Line Plots',
    description: 'Learn about line plots!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '3',
    order: 30,
    estimatedTime: 18,
  },
]

