// Grade 4 Math Curriculum aligned with Khan Academy structure
// Khan Academy Grade 4 Math typically has 18 units

import { Lesson } from './types'
import { getCurriculumVideoUrl } from './video-paths'
import { getDescriptionFromTitle } from './description-from-title'

export interface KhanAcademyUnit {
  id: string
  name: string
  description: string
  order: number
  lessons: Lesson[]
}

export const khanAcademyGrade4Units: KhanAcademyUnit[] = [
  {
    id: 'unit-1-place-value',
    name: 'Place Value',
    description: 'Learn about place value up to millions',
    order: 1,
    lessons: [
      {
        id: 'place-value-intro',
        title: 'What is Place Value?',
        description: 'Learn how numbers are made of ones, tens, hundreds, and more!',
        videoUrl: getCurriculumVideoUrl(1, 1),
        topicId: 'arithmetic',
        grade: '4',
        order: 1,
        estimatedTime: 15,
      },
      {
        id: 'place-value-reading',
        title: 'Reading Big Numbers',
        description: 'Learn to read numbers like 1,234,567!',
        videoUrl: getCurriculumVideoUrl(1, 2),
        topicId: 'arithmetic',
        grade: '4',
        order: 2,
        estimatedTime: 18,
      },
      {
        id: 'place-value-writing',
        title: 'Writing Numbers',
        description: 'Write numbers in different ways!',
        videoUrl: getCurriculumVideoUrl(1, 3),
        topicId: 'arithmetic',
        grade: '4',
        order: 3,
        estimatedTime: 16,
      },
      {
        id: 'place-value-comparing',
        title: 'Comparing Numbers',
        description: 'Learn which number is bigger or smaller!',
        videoUrl: getCurriculumVideoUrl(1, 4),
        topicId: 'arithmetic',
        grade: '4',
        order: 4,
        estimatedTime: 17,
      },
      {
        id: 'place-value-rounding',
        title: 'Rounding Numbers',
        description: 'Make numbers easier by rounding them!',
        videoUrl: getCurriculumVideoUrl(1, 5),
        topicId: 'arithmetic',
        grade: '4',
        order: 5,
        estimatedTime: 20,
      },
    ],
  },
  {
    id: 'unit-2-add-subtract',
    name: 'Addition, Subtraction, and Estimation',
    description: 'Add and subtract big numbers and estimate answers',
    order: 2,
    lessons: [
      {
        id: 'add-subtract-review',
        title: 'Adding and Subtracting Review',
        description: 'Review how to add and subtract!',
        videoUrl: getCurriculumVideoUrl(2, 1),
        topicId: 'arithmetic',
        grade: '4',
        order: 6,
        estimatedTime: 15,
      },
      {
        id: 'add-multi-digit',
        title: 'Adding Big Numbers',
        description: 'Add numbers with many digits!',
        videoUrl: getCurriculumVideoUrl(2, 2),
        topicId: 'arithmetic',
        grade: '4',
        order: 7,
        estimatedTime: 20,
      },
      {
        id: 'subtract-multi-digit',
        title: 'Subtracting Big Numbers',
        description: 'Subtract numbers with many digits!',
        videoUrl: getCurriculumVideoUrl(2, 3),
        topicId: 'arithmetic',
        grade: '4',
        order: 8,
        estimatedTime: 22,
      },
      {
        id: 'estimation',
        title: 'Estimation',
        description: 'Guess the answer before you solve!',
        videoUrl: getCurriculumVideoUrl(2, 4),
        topicId: 'arithmetic',
        grade: '4',
        order: 9,
        estimatedTime: 18,
      },
    ],
  },
  {
    id: 'unit-3-multiply-1-digit',
    name: 'Multiply by 1-Digit Numbers',
    description: 'Learn to multiply by single digit numbers',
    order: 3,
    lessons: [
      {
        id: 'multiply-review',
        title: 'Multiplication Review',
        description: 'Review your times tables!',
        videoUrl: getCurriculumVideoUrl(3, 1),
        topicId: 'arithmetic',
        grade: '4',
        order: 10,
        estimatedTime: 15,
      },
      {
        id: 'multiply-1-digit',
        title: 'Multiply by 1-Digit',
        description: 'Multiply big numbers by 1-digit numbers!',
        videoUrl: getCurriculumVideoUrl(3, 2),
        topicId: 'arithmetic',
        grade: '4',
        order: 11,
        estimatedTime: 22,
      },
      {
        id: 'multiply-word-problems',
        title: 'Multiplication Word Problems',
        description: 'Solve real problems with multiplication!',
        videoUrl: getCurriculumVideoUrl(3, 3),
        topicId: 'arithmetic',
        grade: '4',
        order: 12,
        estimatedTime: 20,
      },
    ],
  },
  {
    id: 'unit-4-multiply-2-digit',
    name: 'Multiply by 2-Digit Numbers',
    description: 'Learn to multiply by two-digit numbers',
    order: 4,
    lessons: [
      {
        id: 'multiply-2-digit-intro',
        title: 'Multiply by 2-Digit Numbers',
        description: 'Learn to multiply by numbers like 23 or 45!',
        videoUrl: getCurriculumVideoUrl(4, 1),
        topicId: 'arithmetic',
        grade: '4',
        order: 13,
        estimatedTime: 25,
      },
      {
        id: 'multiply-2-digit-area',
        title: 'Area Model for Multiplication',
        description: 'Use boxes to help you multiply!',
        videoUrl: getCurriculumVideoUrl(4, 2),
        topicId: 'arithmetic',
        grade: '4',
        order: 14,
        estimatedTime: 23,
      },
      {
        id: 'multiply-2-digit-practice',
        title: 'Practice Multiplying',
        description: 'Get better at multiplying big numbers!',
        videoUrl: getCurriculumVideoUrl(4, 3),
        topicId: 'arithmetic',
        grade: '4',
        order: 15,
        estimatedTime: 20,
      },
    ],
  },
  {
    id: 'unit-5-division',
    name: 'Division',
    description: 'Learn division with remainders and long division',
    order: 5,
    lessons: [
      {
        id: 'division-review',
        title: 'Division Review',
        description: 'Review what division means!',
        videoUrl: getCurriculumVideoUrl(5, 1),
        topicId: 'arithmetic',
        grade: '4',
        order: 16,
        estimatedTime: 15,
      },
      {
        id: 'division-remainders',
        title: 'Division with Remainders',
        description: 'Sometimes numbers don\'t divide evenly!',
        videoUrl: getCurriculumVideoUrl(5, 2),
        topicId: 'arithmetic',
        grade: '4',
        order: 17,
        estimatedTime: 20,
      },
      {
        id: 'long-division',
        title: 'Long Division',
        description: 'Learn the long division method!',
        videoUrl: getCurriculumVideoUrl(5, 3),
        topicId: 'arithmetic',
        grade: '4',
        order: 18,
        estimatedTime: 25,
      },
      {
        id: 'division-word-problems',
        title: 'Division Word Problems',
        description: 'Solve real problems with division!',
        videoUrl: getCurriculumVideoUrl(5, 4),
        topicId: 'arithmetic',
        grade: '4',
        order: 19,
        estimatedTime: 22,
      },
    ],
  },
  {
    id: 'unit-6-factors-multiples',
    name: 'Factors, Multiples, and Patterns',
    description: 'Learn about factors, multiples, and number patterns',
    order: 6,
    lessons: [
      {
        id: 'factors-intro',
        title: 'What are Factors?',
        description: 'Learn what factors are!',
        videoUrl: getCurriculumVideoUrl(6, 1),
        topicId: 'number-theory',
        grade: '4',
        order: 20,
        estimatedTime: 18,
      },
      {
        id: 'multiples-intro',
        title: 'What are Multiples?',
        description: 'Learn what multiples are!',
        videoUrl: getCurriculumVideoUrl(6, 2),
        topicId: 'number-theory',
        grade: '4',
        order: 21,
        estimatedTime: 18,
      },
      {
        id: 'prime-composite',
        title: 'Prime and Composite Numbers',
        description: 'Learn about special numbers!',
        videoUrl: getCurriculumVideoUrl(6, 3),
        topicId: 'number-theory',
        grade: '4',
        order: 22,
        estimatedTime: 20,
      },
      {
        id: 'number-patterns',
        title: 'Number Patterns',
        description: 'Find patterns in numbers!',
        videoUrl: getCurriculumVideoUrl(6, 4),
        topicId: 'number-theory',
        grade: '4',
        order: 23,
        estimatedTime: 19,
      },
    ],
  },
  {
    id: 'unit-7-equivalent-fractions',
    name: 'Equivalent Fractions and Comparing',
    description: 'Learn about equivalent fractions and how to compare them',
    order: 7,
    lessons: [
      {
        id: 'equivalent-fractions-intro',
        title: 'What are Equivalent Fractions?',
        description: 'Learn about fractions that are the same!',
        videoUrl: getCurriculumVideoUrl(7, 1),
        topicId: 'fractions',
        grade: '4',
        order: 24,
        estimatedTime: 20,
      },
      {
        id: 'equivalent-fractions-finding',
        title: 'Finding Equivalent Fractions',
        description: 'How to find fractions that are equal!',
        videoUrl: getCurriculumVideoUrl(7, 2),
        topicId: 'fractions',
        grade: '4',
        order: 25,
        estimatedTime: 22,
      },
      {
        id: 'comparing-fractions',
        title: 'Comparing Fractions',
        description: 'Which fraction is bigger?',
        videoUrl: getCurriculumVideoUrl(7, 3),
        topicId: 'fractions',
        grade: '4',
        order: 26,
        estimatedTime: 23,
      },
      {
        id: 'ordering-fractions',
        title: 'Ordering Fractions',
        description: 'Put fractions in order from smallest to biggest!',
        videoUrl: getCurriculumVideoUrl(7, 4),
        topicId: 'fractions',
        grade: '4',
        order: 27,
        estimatedTime: 21,
      },
    ],
  },
  {
    id: 'unit-8-add-subtract-fractions',
    name: 'Add and Subtract Fractions',
    description: 'Learn to add and subtract fractions',
    order: 8,
    lessons: [
      {
        id: 'add-fractions-like',
        title: 'Adding Fractions with Same Bottom',
        description: 'Add fractions that have the same denominator!',
        videoUrl: getCurriculumVideoUrl(8, 1),
        topicId: 'fractions',
        grade: '4',
        order: 28,
        estimatedTime: 20,
      },
      {
        id: 'subtract-fractions-like',
        title: 'Subtracting Fractions with Same Bottom',
        description: 'Subtract fractions that have the same denominator!',
        videoUrl: getCurriculumVideoUrl(8, 2),
        topicId: 'fractions',
        grade: '4',
        order: 29,
        estimatedTime: 20,
      },
      {
        id: 'add-subtract-mixed',
        title: 'Adding and Subtracting Mixed Numbers',
        description: 'Work with whole numbers and fractions together!',
        videoUrl: getCurriculumVideoUrl(8, 3),
        topicId: 'fractions',
        grade: '4',
        order: 30,
        estimatedTime: 25,
      },
    ],
  },
  {
    id: 'unit-9-multiply-fractions',
    name: 'Multiply Fractions by Whole Numbers',
    description: 'Learn to multiply fractions by whole numbers',
    order: 9,
    lessons: [
      {
        id: 'multiply-fraction-whole',
        title: 'Multiply Fractions by Whole Numbers',
        description: 'Learn to multiply fractions!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'fractions',
        grade: '4',
        order: 31,
        estimatedTime: 22,
      },
      {
        id: 'multiply-fraction-word',
        title: 'Fraction Multiplication Word Problems',
        description: 'Solve real problems with fraction multiplication!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'fractions',
        grade: '4',
        order: 32,
        estimatedTime: 23,
      },
    ],
  },
  {
    id: 'unit-10-decimals',
    name: 'Understand Decimals',
    description: 'Learn about decimals and how they work',
    order: 10,
    lessons: [
      {
        id: 'decimals-intro',
        title: 'Introduction to Decimals',
        description: 'What are decimals?',
        videoUrl: '/assets/demo.mp4',
        topicId: 'fractions',
        grade: '4',
        order: 33,
        estimatedTime: 18,
      },
      {
        id: 'decimal-place-value',
        title: 'Decimal Place Value',
        description: 'Learn about tenths and hundredths!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'fractions',
        grade: '4',
        order: 34,
        estimatedTime: 20,
      },
      {
        id: 'comparing-decimals',
        title: 'Comparing Decimals',
        description: 'Which decimal is bigger?',
        videoUrl: '/assets/demo.mp4',
        topicId: 'fractions',
        grade: '4',
        order: 35,
        estimatedTime: 19,
      },
      {
        id: 'fractions-decimals',
        title: 'Fractions and Decimals',
        description: 'How fractions and decimals are related!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'fractions',
        grade: '4',
        order: 36,
        estimatedTime: 21,
      },
    ],
  },
  {
    id: 'unit-11-plane-figures',
    name: 'Plane Figures',
    description: 'Learn about 2D shapes and their properties',
    order: 11,
    lessons: [
      {
        id: 'shapes-review',
        title: 'Shapes Review',
        description: 'Review different shapes!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 37,
        estimatedTime: 15,
      },
      {
        id: 'quadrilaterals',
        title: 'Quadrilaterals',
        description: 'Learn about 4-sided shapes!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 38,
        estimatedTime: 20,
      },
      {
        id: 'triangles',
        title: 'Triangles',
        description: 'Learn about 3-sided shapes!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 39,
        estimatedTime: 19,
      },
      {
        id: 'lines-symmetry',
        title: 'Lines of Symmetry',
        description: 'Find lines that split shapes in half!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 40,
        estimatedTime: 18,
      },
    ],
  },
  {
    id: 'unit-12-measuring-angles',
    name: 'Measuring Angles',
    description: 'Learn to measure and draw angles',
    order: 12,
    lessons: [
      {
        id: 'angles-intro',
        title: 'What are Angles?',
        description: 'Learn what angles are!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 41,
        estimatedTime: 18,
      },
      {
        id: 'angle-types',
        title: 'Types of Angles',
        description: 'Learn about right, acute, and obtuse angles!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 42,
        estimatedTime: 20,
      },
      {
        id: 'measuring-angles',
        title: 'Measuring Angles',
        description: 'Use a protractor to measure angles!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 43,
        estimatedTime: 22,
      },
      {
        id: 'drawing-angles',
        title: 'Drawing Angles',
        description: 'Learn to draw angles!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 44,
        estimatedTime: 21,
      },
    ],
  },
  {
    id: 'unit-13-area-perimeter',
    name: 'Area and Perimeter',
    description: 'Learn to find area and perimeter of shapes',
    order: 13,
    lessons: [
      {
        id: 'perimeter-intro',
        title: 'What is Perimeter?',
        description: 'Learn what perimeter means!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 45,
        estimatedTime: 18,
      },
      {
        id: 'perimeter-rectangles',
        title: 'Perimeter of Rectangles',
        description: 'Find the perimeter of rectangles!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 46,
        estimatedTime: 20,
      },
      {
        id: 'area-intro',
        title: 'What is Area?',
        description: 'Learn what area means!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 47,
        estimatedTime: 19,
      },
      {
        id: 'area-rectangles',
        title: 'Area of Rectangles',
        description: 'Find the area of rectangles!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 48,
        estimatedTime: 22,
      },
      {
        id: 'area-word-problems',
        title: 'Area and Perimeter Word Problems',
        description: 'Solve real problems with area and perimeter!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'geometry',
        grade: '4',
        order: 49,
        estimatedTime: 23,
      },
    ],
  },
  {
    id: 'unit-14-units-measurement',
    name: 'Units of Measurement',
    description: 'Learn about different units of measurement',
    order: 14,
    lessons: [
      {
        id: 'length-units',
        title: 'Units of Length',
        description: 'Learn about inches, feet, yards, and meters!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 50,
        estimatedTime: 20,
      },
      {
        id: 'weight-units',
        title: 'Units of Weight',
        description: 'Learn about ounces, pounds, and grams!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 51,
        estimatedTime: 19,
      },
      {
        id: 'volume-units',
        title: 'Units of Volume',
        description: 'Learn about cups, pints, quarts, and liters!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 52,
        estimatedTime: 20,
      },
      {
        id: 'converting-units',
        title: 'Converting Units',
        description: 'Change from one unit to another!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 53,
        estimatedTime: 22,
      },
    ],
  },
  {
    id: 'unit-15-time',
    name: 'Time',
    description: 'Learn to tell time and work with time',
    order: 15,
    lessons: [
      {
        id: 'telling-time',
        title: 'Telling Time',
        description: 'Learn to read clocks!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 54,
        estimatedTime: 18,
      },
      {
        id: 'elapsed-time',
        title: 'Elapsed Time',
        description: 'How much time has passed?',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 55,
        estimatedTime: 20,
      },
      {
        id: 'time-word-problems',
        title: 'Time Word Problems',
        description: 'Solve problems about time!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 56,
        estimatedTime: 21,
      },
    ],
  },
  {
    id: 'unit-16-money',
    name: 'Money',
    description: 'Learn about money and making change',
    order: 16,
    lessons: [
      {
        id: 'money-counting',
        title: 'Counting Money',
        description: 'Count coins and bills!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 57,
        estimatedTime: 18,
      },
      {
        id: 'making-change',
        title: 'Making Change',
        description: 'Figure out how much change to give!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 58,
        estimatedTime: 20,
      },
      {
        id: 'money-word-problems',
        title: 'Money Word Problems',
        description: 'Solve problems about money!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 59,
        estimatedTime: 22,
      },
    ],
  },
  {
    id: 'unit-17-data',
    name: 'Represent and Interpret Data',
    description: 'Learn to read and make graphs',
    order: 17,
    lessons: [
      {
        id: 'bar-graphs',
        title: 'Bar Graphs',
        description: 'Read and make bar graphs!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 60,
        estimatedTime: 20,
      },
      {
        id: 'line-plots',
        title: 'Line Plots',
        description: 'Learn about line plots!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 61,
        estimatedTime: 19,
      },
      {
        id: 'pictographs',
        title: 'Pictographs',
        description: 'Read and make pictographs!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'measurement',
        grade: '4',
        order: 62,
        estimatedTime: 18,
      },
    ],
  },
  {
    id: 'unit-18-patterns',
    name: 'Patterns and Problem Solving',
    description: 'Learn about patterns and solve problems',
    order: 18,
    lessons: [
      {
        id: 'number-patterns-advanced',
        title: 'Advanced Number Patterns',
        description: 'Find patterns in number sequences!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'arithmetic',
        grade: '4',
        order: 63,
        estimatedTime: 20,
      },
      {
        id: 'problem-solving',
        title: 'Problem Solving Strategies',
        description: 'Learn different ways to solve problems!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'arithmetic',
        grade: '4',
        order: 64,
        estimatedTime: 22,
      },
      {
        id: 'multi-step-problems',
        title: 'Multi-Step Word Problems',
        description: 'Solve problems that need many steps!',
        videoUrl: '/assets/demo.mp4',
        topicId: 'arithmetic',
        grade: '4',
        order: 65,
        estimatedTime: 25,
      },
    ],
  },
]

// Helper function to get all lessons from all units
export function getAllGrade4Lessons(): Lesson[] {
  return khanAcademyGrade4Units.flatMap(unit => unit.lessons)
}

// Helper function to get lessons by unit
export function getLessonsByUnit(unitId: string): Lesson[] {
  const unit = khanAcademyGrade4Units.find(u => u.id === unitId)
  return unit ? unit.lessons : []
}

// Helper function to get unit by ID
export function getUnitById(unitId: string): KhanAcademyUnit | undefined {
  return khanAcademyGrade4Units.find(u => u.id === unitId)
}

// Ensure every lesson description is derived from its title
khanAcademyGrade4Units.forEach(unit => {
  unit.lessons.forEach(lesson => {
    lesson.description = getDescriptionFromTitle(lesson.title)
  })
})

