// Grade 6 Math Curriculum aligned with Khan Academy structure

import { Lesson } from './types'

export const khanAcademyGrade6Lessons: Lesson[] = [
  // Unit 1: Ratios
  {
    id: 'ratios-intro',
    title: 'Introduction to Ratios',
    description: 'What are ratios?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 1,
    estimatedTime: 20,
  },
  {
    id: 'ratios-visual',
    title: 'Ratios with Pictures',
    description: 'See ratios in pictures!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 2,
    estimatedTime: 19,
  },
  {
    id: 'ratios-equivalent',
    title: 'Equivalent Ratios',
    description: 'Find ratios that are the same!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 3,
    estimatedTime: 21,
  },
  {
    id: 'ratios-word-problems',
    title: 'Ratio Word Problems',
    description: 'Solve real problems with ratios!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 4,
    estimatedTime: 22,
  },

  // Unit 2: Rates
  {
    id: 'rates-intro',
    title: 'Introduction to Rates',
    description: 'What are rates?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 5,
    estimatedTime: 20,
  },
  {
    id: 'unit-rates',
    title: 'Unit Rates',
    description: 'Find rates per one unit!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 6,
    estimatedTime: 21,
  },
  {
    id: 'rates-word-problems',
    title: 'Rate Word Problems',
    description: 'Solve real problems with rates!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 7,
    estimatedTime: 22,
  },

  // Unit 3: Percentages
  {
    id: 'percentages-intro',
    title: 'Introduction to Percentages',
    description: 'What are percentages?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 8,
    estimatedTime: 19,
  },
  {
    id: 'percentages-fractions',
    title: 'Percentages and Fractions',
    description: 'How percentages and fractions are related!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 9,
    estimatedTime: 20,
  },
  {
    id: 'percentages-decimals',
    title: 'Percentages and Decimals',
    description: 'How percentages and decimals are related!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 10,
    estimatedTime: 20,
  },
  {
    id: 'percentages-word-problems',
    title: 'Percentage Word Problems',
    description: 'Solve real problems with percentages!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'ratios',
    grade: '6',
    order: 11,
    estimatedTime: 23,
  },

  // Unit 4: Exponents and Order of Operations
  {
    id: 'exponents-intro',
    title: 'Introduction to Exponents',
    description: 'What are exponents?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '6',
    order: 12,
    estimatedTime: 20,
  },
  {
    id: 'exponents-powers',
    title: 'Powers of 10',
    description: 'Learn about powers of 10!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '6',
    order: 13,
    estimatedTime: 21,
  },
  {
    id: 'order-operations',
    title: 'Order of Operations',
    description: 'Learn the right order to solve problems!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'arithmetic',
    grade: '6',
    order: 14,
    estimatedTime: 22,
  },

  // Unit 5: Negative Numbers
  {
    id: 'negative-numbers-intro',
    title: 'Introduction to Negative Numbers',
    description: 'What are negative numbers?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'negative-numbers',
    grade: '6',
    order: 15,
    estimatedTime: 19,
  },
  {
    id: 'negative-numbers-number-line',
    title: 'Negative Numbers on Number Line',
    description: 'See negative numbers on a number line!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'negative-numbers',
    grade: '6',
    order: 16,
    estimatedTime: 20,
  },
  {
    id: 'negative-numbers-add',
    title: 'Adding Negative Numbers',
    description: 'Learn to add negative numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'negative-numbers',
    grade: '6',
    order: 17,
    estimatedTime: 21,
  },
  {
    id: 'negative-numbers-subtract',
    title: 'Subtracting Negative Numbers',
    description: 'Learn to subtract negative numbers!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'negative-numbers',
    grade: '6',
    order: 18,
    estimatedTime: 21,
  },

  // Unit 6: Variables and Expressions
  {
    id: 'variables-intro',
    title: 'Introduction to Variables',
    description: 'What are variables?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '6',
    order: 19,
    estimatedTime: 20,
  },
  {
    id: 'expressions-intro',
    title: 'Introduction to Expressions',
    description: 'What are expressions?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '6',
    order: 20,
    estimatedTime: 21,
  },
  {
    id: 'expressions-evaluate',
    title: 'Evaluating Expressions',
    description: 'Find the value of expressions!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '6',
    order: 21,
    estimatedTime: 22,
  },
  {
    id: 'expressions-word-problems',
    title: 'Expression Word Problems',
    description: 'Solve real problems with expressions!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '6',
    order: 22,
    estimatedTime: 23,
  },

  // Unit 7: Equations
  {
    id: 'equations-intro',
    title: 'Introduction to Equations',
    description: 'What are equations?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '6',
    order: 23,
    estimatedTime: 20,
  },
  {
    id: 'one-step-equations',
    title: 'One-Step Equations',
    description: 'Solve equations with one step!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '6',
    order: 24,
    estimatedTime: 22,
  },
  {
    id: 'equations-word-problems',
    title: 'Equation Word Problems',
    description: 'Solve real problems with equations!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '6',
    order: 25,
    estimatedTime: 23,
  },

  // Unit 8: Inequalities
  {
    id: 'inequalities-intro',
    title: 'Introduction to Inequalities',
    description: 'What are inequalities?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '6',
    order: 26,
    estimatedTime: 20,
  },
  {
    id: 'inequalities-solve',
    title: 'Solving Inequalities',
    description: 'Learn to solve inequalities!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'algebra',
    grade: '6',
    order: 27,
    estimatedTime: 21,
  },

  // Unit 9: Geometry - Area
  {
    id: 'area-triangles',
    title: 'Area of Triangles',
    description: 'Find the area of triangles!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '6',
    order: 28,
    estimatedTime: 22,
  },
  {
    id: 'area-parallelograms',
    title: 'Area of Parallelograms',
    description: 'Find the area of parallelograms!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '6',
    order: 29,
    estimatedTime: 21,
  },
  {
    id: 'area-trapezoids',
    title: 'Area of Trapezoids',
    description: 'Find the area of trapezoids!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '6',
    order: 30,
    estimatedTime: 22,
  },
  {
    id: 'area-composite',
    title: 'Area of Composite Shapes',
    description: 'Find the area of complex shapes!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '6',
    order: 31,
    estimatedTime: 24,
  },

  // Unit 10: Geometry - Surface Area and Volume
  {
    id: 'surface-area-intro',
    title: 'Introduction to Surface Area',
    description: 'What is surface area?',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '6',
    order: 32,
    estimatedTime: 21,
  },
  {
    id: 'surface-area-rectangular',
    title: 'Surface Area of Rectangular Prisms',
    description: 'Find the surface area of boxes!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '6',
    order: 33,
    estimatedTime: 23,
  },
  {
    id: 'volume-rectangular',
    title: 'Volume of Rectangular Prisms',
    description: 'Find the volume of boxes!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'geometry',
    grade: '6',
    order: 34,
    estimatedTime: 22,
  },

  // Unit 11: Statistics
  {
    id: 'statistics-mean',
    title: 'Mean (Average)',
    description: 'Learn to find the average!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '6',
    order: 35,
    estimatedTime: 20,
  },
  {
    id: 'statistics-median',
    title: 'Median',
    description: 'Learn to find the middle number!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '6',
    order: 36,
    estimatedTime: 20,
  },
  {
    id: 'statistics-mode',
    title: 'Mode',
    description: 'Learn to find the most common number!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '6',
    order: 37,
    estimatedTime: 19,
  },
  {
    id: 'statistics-range',
    title: 'Range',
    description: 'Learn to find the range!',
    videoUrl: '/assets/demo.mp4',
    topicId: 'measurement',
    grade: '6',
    order: 38,
    estimatedTime: 19,
  },
]

