// Comprehensive math curriculum for grades 3-8 based on Khan Academy structure

export interface Topic {
  id: string
  name: string
  description: string
  icon: string
  grades: string[]
}

export interface Lesson {
  id: string
  title: string
  description: string
  videoUrl: string
  topicId: string
  grade: string
  order: number
  estimatedTime: number // in minutes
}

export const topics: Topic[] = [
  {
    id: 'arithmetic',
    name: 'Arithmetic',
    description: 'Basic operations and number sense',
    icon: '➕',
    grades: ['3', '4', '5', '6'],
  },
  {
    id: 'fractions',
    name: 'Fractions & Decimals',
    description: 'Understanding and working with fractions and decimals',
    icon: '➗',
    grades: ['3', '4', '5', '6'],
  },
  {
    id: 'geometry',
    name: 'Geometry',
    description: 'Shapes, angles, area, and perimeter',
    icon: '🔺',
    grades: ['3', '4', '5', '6', '7', '8'],
  },
  {
    id: 'measurement',
    name: 'Measurement & Data',
    description: 'Units, time, graphs, and statistics',
    icon: '📏',
    grades: ['3', '4', '5', '6'],
  },
  {
    id: 'algebra',
    name: 'Algebra',
    description: 'Expressions, equations, and variables',
    icon: '📝',
    grades: ['6', '7', '8'],
  },
  {
    id: 'ratios',
    name: 'Ratios & Proportions',
    description: 'Understanding ratios, rates, and proportions',
    icon: '⚖️',
    grades: ['6', '7', '8'],
  },
  {
    id: 'number-theory',
    name: 'Number Theory',
    description: 'Factors, multiples, prime numbers',
    icon: '🔍',
    grades: ['4', '5', '6'],
  },
  {
    id: 'negative-numbers',
    name: 'Negative Numbers',
    description: 'Working with negative numbers and integers',
    icon: '➖',
    grades: ['6', '7', '8'],
  },
]

export const lessons: Lesson[] = [
  // Grade 3 - Arithmetic
  {
    id: 'add-subtract-3',
    title: 'Add & Subtract to 1000',
    description: 'Master adding and subtracting big numbers! 🎯',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '3',
    order: 1,
    estimatedTime: 15,
  },
  {
    id: 'multiplication-intro',
    title: 'What is Multiplication?',
    description: 'Learn multiplication with fun groups! 🎈',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '3',
    order: 2,
    estimatedTime: 18,
  },
  {
    id: 'multiplication-tables',
    title: 'Times Tables Fun!',
    description: 'Master your multiplication facts! ⚡',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '3',
    order: 3,
    estimatedTime: 20,
  },
  {
    id: 'division-intro',
    title: 'Sharing is Caring!',
    description: 'Learn division by sharing equally! 🍕',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '3',
    order: 4,
    estimatedTime: 18,
  },
  {
    id: 'rounding-numbers',
    title: 'Round It Up!',
    description: 'Make numbers friendly by rounding! 🔢',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '3',
    order: 5,
    estimatedTime: 15,
  },

  // Grade 3 - Fractions
  {
    id: 'fractions-intro',
    title: 'Pizza Fractions!',
    description: 'Learn fractions with yummy pizza slices! 🍕',
    videoUrl: 'https://www.youtube.com/embed/n0FZhQ_GkKw', // Khan Academy: Intro to fractions
    topicId: 'fractions',
    grade: '3',
    order: 6,
    estimatedTime: 18,
  },
  {
    id: 'fractions-visual',
    title: 'Fractions on a Line',
    description: 'Put fractions on number lines! 📏',
    videoUrl: 'https://www.youtube.com/embed/lN_bvHvBhcs', // Khan Academy: Fractions on number line
    topicId: 'fractions',
    grade: '3',
    order: 7,
    estimatedTime: 16,
  },
  {
    id: 'equivalent-fractions-basic',
    title: 'Same but Different!',
    description: 'Find fractions that are equal! 🎯',
    videoUrl: 'https://www.youtube.com/embed/BI0orN0Im4s', // Khan Academy: Equivalent fractions
    topicId: 'fractions',
    grade: '3',
    order: 8,
    estimatedTime: 17,
  },

  // Grade 3 - Geometry
  {
    id: 'shapes-2d',
    title: 'Fun with Shapes!',
    description: 'Discover circles, squares, and triangles! 🔺',
    videoUrl: 'https://www.youtube.com/embed/2cg-Uc556-Q', // Khan Academy: Recognizing shapes
    topicId: 'geometry',
    grade: '3',
    order: 9,
    estimatedTime: 16,
  },
  {
    id: 'perimeter',
    title: 'Walk Around Shapes!',
    description: 'Find the distance around shapes! 🚶',
    videoUrl: 'https://www.youtube.com/embed/AAY1bsazcgM', // Khan Academy: Perimeter
    topicId: 'geometry',
    grade: '3',
    order: 10,
    estimatedTime: 18,
  },
  {
    id: 'area-intro',
    title: 'How Much Space?',
    description: 'Learn about area by counting squares! 📦',
    videoUrl: 'https://www.youtube.com/embed/xCdxURXMdFY', // Khan Academy: Intro to area
    topicId: 'geometry',
    grade: '3',
    order: 11,
    estimatedTime: 17,
  },
  {
    id: 'area-rectangles',
    title: 'Rectangle Area Magic!',
    description: 'Multiply to find rectangle area! ✨',
    videoUrl: 'https://www.youtube.com/embed/xCdxURXMdFY', // Khan Academy: Area of rectangles
    topicId: 'geometry',
    grade: '3',
    order: 12,
    estimatedTime: 16,
  },

  // Grade 3 - Measurement & Data
  {
    id: 'time-telling',
    title: 'What Time Is It?',
    description: 'Learn to tell time on clocks! ⏰',
    videoUrl: 'https://www.youtube.com/embed/h6RNkQ7x2qY', // Khan Academy: Telling time
    topicId: 'measurement',
    grade: '3',
    order: 13,
    estimatedTime: 17,
  },
  {
    id: 'mass-volume',
    title: 'Weigh & Measure!',
    description: 'Compare weights and volumes! ⚖️',
    videoUrl: 'https://www.youtube.com/embed/2z7y7LwZb2k', // Khan Academy: Mass and volume
    topicId: 'measurement',
    grade: '3',
    order: 14,
    estimatedTime: 16,
  },
  {
    id: 'bar-graphs',
    title: 'Graph Adventures!',
    description: 'Read and make cool graphs! 📊',
    videoUrl: 'https://www.youtube.com/embed/9Uc62CuQjc4', // Khan Academy: Bar graphs
    topicId: 'measurement',
    grade: '3',
    order: 15,
    estimatedTime: 18,
  },

  // Grade 4 - Arithmetic
  {
    id: 'multi-digit-multiply',
    title: 'Multi-Digit Multiplication',
    description: 'Multiply larger numbers using different methods',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '4',
    order: 1,
    estimatedTime: 25,
  },
  {
    id: 'long-division',
    title: 'Long Division',
    description: 'Divide larger numbers step by step',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '4',
    order: 2,
    estimatedTime: 25,
  },
  {
    id: 'factors-multiples',
    title: 'Factors and Multiples',
    description: 'Understand factors, multiples, and prime numbers',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'number-theory',
    grade: '4',
    order: 3,
    estimatedTime: 20,
  },

  // Grade 4 - Fractions
  {
    id: 'equivalent-fractions',
    title: 'Equivalent Fractions',
    description: 'Find fractions that represent the same value',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '4',
    order: 4,
    estimatedTime: 22,
  },
  {
    id: 'comparing-fractions',
    title: 'Comparing Fractions',
    description: 'Compare fractions using different strategies',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '4',
    order: 5,
    estimatedTime: 20,
  },
  {
    id: 'adding-fractions',
    title: 'Adding and Subtracting Fractions',
    description: 'Add and subtract fractions with like denominators',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '4',
    order: 6,
    estimatedTime: 25,
  },
  {
    id: 'decimals-intro',
    title: 'Introduction to Decimals',
    description: 'Understand decimals and place value',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '4',
    order: 7,
    estimatedTime: 20,
  },

  // Grade 4 - Geometry
  {
    id: 'angles',
    title: 'Angles',
    description: 'Identify and measure angles',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '4',
    order: 8,
    estimatedTime: 18,
  },
  {
    id: 'area-rectangles',
    title: 'Area of Rectangles',
    description: 'Calculate area using length and width',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '4',
    order: 9,
    estimatedTime: 20,
  },

  // Grade 5 - Unit 1: Decimal Place Value (Khan Academy aligned)
  {
    id: 'decimal-place-value-intro',
    title: 'Introduction to Decimals',
    description: 'Understand decimal place value and how decimals work',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 1,
    estimatedTime: 20,
  },
  {
    id: 'decimal-place-value-tenths',
    title: 'Tenths and Hundredths',
    description: 'Work with tenths and hundredths place values',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 2,
    estimatedTime: 18,
  },
  {
    id: 'decimal-place-value-thousandths',
    title: 'Thousandths Place',
    description: 'Understand and work with thousandths',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 3,
    estimatedTime: 20,
  },
  {
    id: 'comparing-decimals',
    title: 'Comparing Decimals',
    description: 'Compare decimals using place value',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 4,
    estimatedTime: 18,
  },
  {
    id: 'rounding-decimals',
    title: 'Rounding Decimals',
    description: 'Round decimals to any place value',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 5,
    estimatedTime: 20,
  },
  {
    id: 'decimal-number-line',
    title: 'Decimals on Number Line',
    description: 'Place and identify decimals on number lines',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 6,
    estimatedTime: 18,
  },

  // Grade 5 - Unit 2: Add Decimals
  {
    id: 'add-decimals-tenths',
    title: 'Adding Decimals: Tenths',
    description: 'Add decimals in the tenths place',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 7,
    estimatedTime: 20,
  },
  {
    id: 'add-decimals-hundredths',
    title: 'Adding Decimals: Hundredths',
    description: 'Add decimals with hundredths place',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 8,
    estimatedTime: 22,
  },
  {
    id: 'add-decimals-mixed',
    title: 'Adding Mixed Decimals',
    description: 'Add decimals with different place values',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 9,
    estimatedTime: 20,
  },
  {
    id: 'add-decimals-word-problems',
    title: 'Adding Decimals: Word Problems',
    description: 'Solve real-world problems with decimal addition',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 10,
    estimatedTime: 22,
  },
  {
    id: 'add-decimals-estimation',
    title: 'Estimating Decimal Sums',
    description: 'Estimate sums before adding decimals',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 11,
    estimatedTime: 18,
  },

  // Grade 5 - Unit 3: Subtract Decimals
  {
    id: 'subtract-decimals-tenths',
    title: 'Subtracting Decimals: Tenths',
    description: 'Subtract decimals in the tenths place',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 12,
    estimatedTime: 20,
  },
  {
    id: 'subtract-decimals-hundredths',
    title: 'Subtracting Decimals: Hundredths',
    description: 'Subtract decimals with hundredths place',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 13,
    estimatedTime: 22,
  },
  {
    id: 'subtract-decimals-borrowing',
    title: 'Subtracting Decimals with Borrowing',
    description: 'Subtract decimals that require borrowing',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 14,
    estimatedTime: 23,
  },
  {
    id: 'subtract-decimals-word-problems',
    title: 'Subtracting Decimals: Word Problems',
    description: 'Solve real-world problems with decimal subtraction',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 15,
    estimatedTime: 22,
  },
  {
    id: 'subtract-decimals-estimation',
    title: 'Estimating Decimal Differences',
    description: 'Estimate differences before subtracting decimals',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 16,
    estimatedTime: 18,
  },

  // Grade 5 - Unit 4: Multi-Digit Multiplication
  {
    id: 'multiply-2-digit',
    title: 'Multiplying 2-Digit Numbers',
    description: 'Multiply two-digit numbers using standard algorithm',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 17,
    estimatedTime: 25,
  },
  {
    id: 'multiply-3-digit',
    title: 'Multiplying 3-Digit Numbers',
    description: 'Multiply three-digit numbers',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 18,
    estimatedTime: 28,
  },
  {
    id: 'multiply-area-model',
    title: 'Multiplication: Area Model',
    description: 'Use area model to multiply large numbers',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 19,
    estimatedTime: 25,
  },
  {
    id: 'multiply-distributive',
    title: 'Multiplication: Distributive Property',
    description: 'Use distributive property to multiply',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 20,
    estimatedTime: 22,
  },
  {
    id: 'multiply-word-problems',
    title: 'Multiplication: Word Problems',
    description: 'Solve multi-step word problems with multiplication',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 21,
    estimatedTime: 25,
  },
  {
    id: 'multiply-estimation',
    title: 'Estimating Products',
    description: 'Estimate products before multiplying',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 22,
    estimatedTime: 20,
  },

  // Grade 5 - Unit 5: Multi-Digit Division
  {
    id: 'divide-2-digit',
    title: 'Dividing by 2-Digit Numbers',
    description: 'Divide using long division with 2-digit divisors',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 23,
    estimatedTime: 28,
  },
  {
    id: 'divide-remainders',
    title: 'Division with Remainders',
    description: 'Handle remainders in division problems',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 24,
    estimatedTime: 25,
  },
  {
    id: 'divide-partial-quotients',
    title: 'Division: Partial Quotients',
    description: 'Use partial quotients method for division',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 25,
    estimatedTime: 26,
  },
  {
    id: 'divide-word-problems',
    title: 'Division: Word Problems',
    description: 'Solve word problems using division',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 26,
    estimatedTime: 25,
  },
  {
    id: 'divide-estimation',
    title: 'Estimating Quotients',
    description: 'Estimate quotients before dividing',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 27,
    estimatedTime: 20,
  },

  // Grade 5 - Unit 6: Powers of 10
  {
    id: 'powers-ten-intro',
    title: 'Introduction to Powers of 10',
    description: 'Understand what powers of 10 mean',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 28,
    estimatedTime: 20,
  },
  {
    id: 'multiply-powers-ten',
    title: 'Multiplying by Powers of 10',
    description: 'Multiply numbers by 10, 100, 1000, etc.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 29,
    estimatedTime: 22,
  },
  {
    id: 'divide-powers-ten',
    title: 'Dividing by Powers of 10',
    description: 'Divide numbers by 10, 100, 1000, etc.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 30,
    estimatedTime: 22,
  },
  {
    id: 'powers-ten-patterns',
    title: 'Patterns with Powers of 10',
    description: 'Identify patterns when working with powers of 10',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 31,
    estimatedTime: 20,
  },
  {
    id: 'powers-ten-word-problems',
    title: 'Powers of 10: Word Problems',
    description: 'Apply powers of 10 to real-world situations',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'arithmetic',
    grade: '5',
    order: 32,
    estimatedTime: 22,
  },

  // Grade 5 - Unit 7: Multiply Decimals
  {
    id: 'multiply-decimals-tenths',
    title: 'Multiplying Decimals: Tenths',
    description: 'Multiply decimals in the tenths place',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 33,
    estimatedTime: 25,
  },
  {
    id: 'multiply-decimals-hundredths',
    title: 'Multiplying Decimals: Hundredths',
    description: 'Multiply decimals with hundredths',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 34,
    estimatedTime: 26,
  },
  {
    id: 'multiply-decimals-mixed',
    title: 'Multiplying Mixed Decimals',
    description: 'Multiply decimals with different place values',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 35,
    estimatedTime: 27,
  },
  {
    id: 'multiply-decimals-word-problems',
    title: 'Multiplying Decimals: Word Problems',
    description: 'Solve word problems with decimal multiplication',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 36,
    estimatedTime: 25,
  },
  {
    id: 'multiply-decimals-estimation',
    title: 'Estimating Decimal Products',
    description: 'Estimate products when multiplying decimals',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 37,
    estimatedTime: 22,
  },

  // Grade 5 - Unit 8: Divide Decimals
  {
    id: 'divide-decimals-tenths',
    title: 'Dividing Decimals: Tenths',
    description: 'Divide decimals in the tenths place',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 38,
    estimatedTime: 25,
  },
  {
    id: 'divide-decimals-hundredths',
    title: 'Dividing Decimals: Hundredths',
    description: 'Divide decimals with hundredths',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 39,
    estimatedTime: 26,
  },
  {
    id: 'divide-decimals-whole-numbers',
    title: 'Dividing Decimals by Whole Numbers',
    description: 'Divide decimals by whole numbers',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 40,
    estimatedTime: 27,
  },
  {
    id: 'divide-decimals-word-problems',
    title: 'Dividing Decimals: Word Problems',
    description: 'Solve word problems with decimal division',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 41,
    estimatedTime: 25,
  },
  {
    id: 'divide-decimals-estimation',
    title: 'Estimating Decimal Quotients',
    description: 'Estimate quotients when dividing decimals',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 42,
    estimatedTime: 22,
  },

  // Grade 5 - Unit 9: Add and Subtract Fractions
  {
    id: 'add-fractions-like-denominators',
    title: 'Adding Fractions: Like Denominators',
    description: 'Add fractions with the same denominator',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 43,
    estimatedTime: 22,
  },
  {
    id: 'subtract-fractions-like-denominators',
    title: 'Subtracting Fractions: Like Denominators',
    description: 'Subtract fractions with the same denominator',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 44,
    estimatedTime: 22,
  },
  {
    id: 'add-fractions-unlike-denominators',
    title: 'Adding Fractions: Unlike Denominators',
    description: 'Add fractions with different denominators',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 45,
    estimatedTime: 28,
  },
  {
    id: 'subtract-fractions-unlike-denominators',
    title: 'Subtracting Fractions: Unlike Denominators',
    description: 'Subtract fractions with different denominators',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 46,
    estimatedTime: 28,
  },
  {
    id: 'add-subtract-mixed-numbers',
    title: 'Adding and Subtracting Mixed Numbers',
    description: 'Work with mixed numbers in addition and subtraction',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 47,
    estimatedTime: 30,
  },
  {
    id: 'fractions-word-problems',
    title: 'Fractions: Word Problems',
    description: 'Solve word problems with fraction addition and subtraction',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 48,
    estimatedTime: 25,
  },

  // Grade 5 - Unit 10: Multiply Fractions
  {
    id: 'multiplying-fractions',
    title: 'Multiplying Fractions',
    description: 'Multiply fractions and mixed numbers',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 49,
    estimatedTime: 25,
  },
  {
    id: 'multiply-fractions-visual',
    title: 'Multiplying Fractions: Visual Models',
    description: 'Use area models to multiply fractions',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 50,
    estimatedTime: 26,
  },
  {
    id: 'multiply-fractions-mixed',
    title: 'Multiplying Mixed Numbers',
    description: 'Multiply mixed numbers and fractions',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 51,
    estimatedTime: 28,
  },
  {
    id: 'multiply-fractions-word-problems',
    title: 'Multiplying Fractions: Word Problems',
    description: 'Solve word problems with fraction multiplication',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 52,
    estimatedTime: 25,
  },
  {
    id: 'multiply-fractions-estimation',
    title: 'Estimating Fraction Products',
    description: 'Estimate products when multiplying fractions',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 53,
    estimatedTime: 22,
  },

  // Grade 5 - Unit 11: Divide Fractions
  {
    id: 'dividing-fractions',
    title: 'Dividing Fractions',
    description: 'Divide fractions using reciprocal method',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 54,
    estimatedTime: 25,
  },
  {
    id: 'divide-fractions-visual',
    title: 'Dividing Fractions: Visual Models',
    description: 'Use visual models to understand fraction division',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 55,
    estimatedTime: 26,
  },
  {
    id: 'divide-fractions-mixed',
    title: 'Dividing Mixed Numbers',
    description: 'Divide mixed numbers and fractions',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 56,
    estimatedTime: 28,
  },
  {
    id: 'divide-fractions-word-problems',
    title: 'Dividing Fractions: Word Problems',
    description: 'Solve word problems with fraction division',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 57,
    estimatedTime: 25,
  },
  {
    id: 'divide-fractions-estimation',
    title: 'Estimating Fraction Quotients',
    description: 'Estimate quotients when dividing fractions',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 58,
    estimatedTime: 22,
  },

  // Grade 5 - Unit 12: Converting Fractions and Decimals
  {
    id: 'fractions-decimals',
    title: 'Converting Fractions and Decimals',
    description: 'Convert between fractions and decimals',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 59,
    estimatedTime: 22,
  },
  {
    id: 'fraction-to-decimal',
    title: 'Fraction to Decimal',
    description: 'Convert fractions to decimal form',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 60,
    estimatedTime: 23,
  },
  {
    id: 'decimal-to-fraction',
    title: 'Decimal to Fraction',
    description: 'Convert decimals to fraction form',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 61,
    estimatedTime: 23,
  },
  {
    id: 'fractions-decimals-equivalent',
    title: 'Equivalent Fractions and Decimals',
    description: 'Find equivalent fractions and decimals',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 62,
    estimatedTime: 24,
  },
  {
    id: 'fractions-decimals-word-problems',
    title: 'Fractions & Decimals: Word Problems',
    description: 'Solve problems using fraction and decimal conversions',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'fractions',
    grade: '5',
    order: 63,
    estimatedTime: 25,
  },

  // Grade 5 - Unit 13: Volume
  {
    id: 'volume',
    title: 'Volume',
    description: 'Calculate volume of rectangular prisms',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '5',
    order: 64,
    estimatedTime: 20,
  },
  {
    id: 'volume-formula',
    title: 'Volume Formula',
    description: 'Use formula V = l × w × h to find volume',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '5',
    order: 65,
    estimatedTime: 22,
  },
  {
    id: 'volume-unit-cubes',
    title: 'Volume with Unit Cubes',
    description: 'Find volume by counting unit cubes',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '5',
    order: 66,
    estimatedTime: 23,
  },
  {
    id: 'volume-composite',
    title: 'Volume of Composite Shapes',
    description: 'Find volume of shapes made of multiple prisms',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '5',
    order: 67,
    estimatedTime: 25,
  },
  {
    id: 'volume-word-problems',
    title: 'Volume: Word Problems',
    description: 'Solve real-world problems involving volume',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '5',
    order: 68,
    estimatedTime: 24,
  },

  // Grade 5 - Unit 14: Coordinate Plane
  {
    id: 'coordinate-plane',
    title: 'Coordinate Plane',
    description: 'Plot points and understand coordinates',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '5',
    order: 69,
    estimatedTime: 18,
  },
  {
    id: 'coordinate-plane-quadrants',
    title: 'Quadrants of Coordinate Plane',
    description: 'Understand the four quadrants',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '5',
    order: 70,
    estimatedTime: 20,
  },
  {
    id: 'coordinate-plane-plotting',
    title: 'Plotting Points',
    description: 'Plot points on the coordinate plane',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '5',
    order: 71,
    estimatedTime: 20,
  },
  {
    id: 'coordinate-plane-reading',
    title: 'Reading Coordinates',
    description: 'Read and identify coordinates of points',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '5',
    order: 72,
    estimatedTime: 19,
  },
  {
    id: 'coordinate-plane-patterns',
    title: 'Patterns on Coordinate Plane',
    description: 'Identify patterns and relationships on coordinate plane',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '5',
    order: 73,
    estimatedTime: 22,
  },

  // Grade 6 - Arithmetic
  {
    id: 'negative-numbers-intro',
    title: 'Introduction to Negative Numbers',
    description: 'Understand negative numbers on a number line',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'negative-numbers',
    grade: '6',
    order: 1,
    estimatedTime: 20,
  },
  {
    id: 'negative-operations',
    title: 'Operations with Negative Numbers',
    description: 'Add, subtract, multiply, and divide negative numbers',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'negative-numbers',
    grade: '6',
    order: 2,
    estimatedTime: 25,
  },

  // Grade 6 - Ratios
  {
    id: 'ratios-intro',
    title: 'Understanding Ratios',
    description: 'Learn what ratios are and how to write them',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'ratios',
    grade: '6',
    order: 3,
    estimatedTime: 20,
  },
  {
    id: 'rates',
    title: 'Rates and Unit Rates',
    description: 'Calculate and compare rates',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'ratios',
    grade: '6',
    order: 4,
    estimatedTime: 22,
  },
  {
    id: 'percentages',
    title: 'Percentages',
    description: 'Understand and calculate percentages',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'ratios',
    grade: '6',
    order: 5,
    estimatedTime: 25,
  },

  // Grade 6 - Algebra
  {
    id: 'variables-expressions',
    title: 'Variables and Expressions',
    description: 'Introduction to variables and algebraic expressions',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'algebra',
    grade: '6',
    order: 6,
    estimatedTime: 22,
  },
  {
    id: 'one-step-equations',
    title: 'One-Step Equations',
    description: 'Solve simple equations with one operation',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'algebra',
    grade: '6',
    order: 7,
    estimatedTime: 25,
  },

  // Grade 6 - Geometry
  {
    id: 'area-triangles',
    title: 'Area of Triangles',
    description: 'Calculate area of triangles',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '6',
    order: 8,
    estimatedTime: 20,
  },
  {
    id: 'area-circles',
    title: 'Area and Circumference of Circles',
    description: 'Use pi to find area and circumference',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '6',
    order: 9,
    estimatedTime: 22,
  },

  // Grade 7 - Algebra
  {
    id: 'two-step-equations',
    title: 'Two-Step Equations',
    description: 'Solve equations requiring two operations',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'algebra',
    grade: '7',
    order: 1,
    estimatedTime: 25,
  },
  {
    id: 'inequalities',
    title: 'Inequalities',
    description: 'Solve and graph inequalities',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'algebra',
    grade: '7',
    order: 2,
    estimatedTime: 25,
  },
  {
    id: 'linear-equations',
    title: 'Linear Equations',
    description: 'Graph and solve linear equations',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'algebra',
    grade: '7',
    order: 3,
    estimatedTime: 28,
  },

  // Grade 7 - Ratios
  {
    id: 'proportions',
    title: 'Proportions',
    description: 'Set up and solve proportions',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'ratios',
    grade: '7',
    order: 4,
    estimatedTime: 25,
  },
  {
    id: 'percent-change',
    title: 'Percent Change',
    description: 'Calculate percent increase and decrease',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'ratios',
    grade: '7',
    order: 5,
    estimatedTime: 22,
  },

  // Grade 7 - Geometry
  {
    id: 'scale-drawings',
    title: 'Scale Drawings',
    description: 'Understand and create scale drawings',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '7',
    order: 6,
    estimatedTime: 20,
  },
  {
    id: 'surface-area',
    title: 'Surface Area',
    description: 'Calculate surface area of 3D shapes',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '7',
    order: 7,
    estimatedTime: 25,
  },

  // Grade 8 - Algebra
  {
    id: 'multi-step-equations',
    title: 'Multi-Step Equations',
    description: 'Solve complex equations with multiple steps',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'algebra',
    grade: '8',
    order: 1,
    estimatedTime: 28,
  },
  {
    id: 'systems-equations',
    title: 'Systems of Equations',
    description: 'Solve systems using substitution and elimination',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'algebra',
    grade: '8',
    order: 2,
    estimatedTime: 30,
  },
  {
    id: 'quadratic-intro',
    title: 'Introduction to Quadratics',
    description: 'Understand quadratic expressions and equations',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'algebra',
    grade: '8',
    order: 3,
    estimatedTime: 25,
  },

  // Grade 8 - Geometry
  {
    id: 'pythagorean-theorem',
    title: 'Pythagorean Theorem',
    description: 'Use the Pythagorean theorem to find side lengths',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '8',
    order: 4,
    estimatedTime: 25,
  },
  {
    id: 'transformations',
    title: 'Transformations',
    description: 'Reflections, rotations, and translations',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '8',
    order: 5,
    estimatedTime: 28,
  },
  {
    id: 'similarity',
    title: 'Similarity and Congruence',
    description: 'Identify similar and congruent figures',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    topicId: 'geometry',
    grade: '8',
    order: 6,
    estimatedTime: 25,
  },
]

export const getLessonsByGrade = (grade: string | number): Lesson[] => {
  const gradeStr = String(grade)
  return lessons.filter((lesson) => String(lesson.grade) === gradeStr).sort((a, b) => a.order - b.order)
}

export const getLessonsByTopic = (topicId: string, grade: string | number): Lesson[] => {
  const gradeStr = String(grade)
  return lessons
    .filter((lesson) => lesson.topicId === topicId && String(lesson.grade) === gradeStr)
    .sort((a, b) => a.order - b.order)
}

export const getTopicsByGrade = (grade: string | number): Topic[] => {
  const gradeStr = String(grade)
  return topics.filter((topic) => topic.grades.includes(gradeStr))
}

export const getLessonById = (lessonId: string): Lesson | undefined => {
  return lessons.find((lesson) => lesson.id === lessonId)
}

export const getTopicById = (topicId: string): Topic | undefined => {
  return topics.find((topic) => topic.id === topicId)
}

